#!/bin/bash
#SBATCH -J minirocket_multiclass      	# Job name
#SBATCH -o training_outputs/minirocket_multiclass_v2%j.out              	# output file (%j expands to jobID)
#SBATCH -e training_outputs/minirocket_multiclass_v2%j.err              	# error log file (%j expands to jobID)
#SBATCH --mail-type=ALL                  	# Request status by email
#SBATCH --mail-user=sjl356@cornell.edu.   	# Email address to send results to.
#SBATCH -N 1                             	# Total number of nodes requested
#SBATCH -n 8                             	# Total number of cores requested
#SBATCH --get-user-env                   	# retrieve the users login environment
#SBATCH --mem=32gb                   	# server memory requested (per node)
#SBATCH -t 96:00:00                       	# Time limit (hh:mm:ss)
#SBATCH --gres=gpu:1              	# Type/number of GPUs needed
#SBATCH --partition=gpu


#export your required environment variables below
#################################################



python3 all_models.py